channels:
  - conda-forge
  - nsls2forge
dependencies:
  - amostra
  - area-detector-handlers
  - bokeh
  - boto3
  - bottleneck
  - chxtools
  - csxtools>=0.1.14
  - dask-image
  # - dask-labextension  # front-end cannot connect, unsure why
  - dask-ml
  - dask-xgboost
  - dask
  - eiger-io
  - fabio
  - graphviz
  - h5py
  - hxntools
  - ipympl
  - jupyterlab=3.*
  - line_profiler
  - lmfit>=0.9.9
  - matplotlib
  - memory_profiler
  - mendeleev
  - modestimage
  - nbgitpuller
  - nbserverproxy
  - netcdf4
  - nodejs
  - nomkl
  - notebook
  - nslsii
  - numba
  - numexpr
  - numpy
  - pandas
  - papermill
  - periodictable
  - photutils
  - pip
  - py-xgboost
  - py4xs
  - pyarrow
  - pychx
  - pyfai
  - pypdf2
  - pystackreg
  - python-graphviz
  - python=3.7
  - pyxrf>=0.0.9
  - reportlab
  - requests
  - sasview
  - scikit-learn
  - scikit-learn
  - scikit-learn
  - seaborn
  - sip
  - sixtools>=0.0.2
  - tomopy
  - tornado
  - voila
  - xarray
  # xpdan
  - xray-vision
  - xraylarch>=0.9.45
  - pip:
    # - edrixs
    - mimesis
    - pyzbar
