channels:
  - conda-forge
  - nsls2forge
dependencies:
  - amostra
  - area-detector-handlers
  - bokeh=1.4.0
  - boto3
  - bottleneck
  - chxtools
  - csxtools>=0.1.14
  - dask-image=0.2.0
  - dask-labextension
  - dask-ml=1.2.0
  - dask-xgboost
  - dask=2.9.1
  - eiger-io
  - fabio
  - graphviz
  - h5py
  - hxntools
  - ipympl
  # TODO: Bump jupyterlab to 3.x once binder does.
  - jupyterlab=2.*
  - line_profiler
  - lmfit>=0.9.9
  - matplotlib
  - memory_profiler
  - mendeleev
  - modestimage
  - nbgitpuller
  - nbserverproxy
  - netcdf4
  - nodejs
  - nomkl
  - notebook
  - nslsii
  - numba
  - numexpr
  - numpy
  - pandas
  - papermill
  - periodictable
  - pip
  - py-xgboost
  - py4xs
  - pyarrow
  - pyfai
  - pypdf2
  - pystackreg
  - python-graphviz
  - python=3.7
  - pyxrf>=0.0.9
  - reportlab
  - requests
  - sasview
  - scikit-learn
  - scikit-learn
  - scikit-learn
  - seaborn
  - sixtools>=0.0.2
  - tomopy
  - tornado=5
  - voila
  - xarray
  # xpdan
  - xraylarch>=0.9.45
  - pip:
    # - edrixs
    - mimesis
    - pyzbar
    - tiled>=0.1.0a12
    - git+https://github.com/bluesky/databroker.git@tiled-refactor#egg=databroker[complete]
