channels:
  - defaults
  - nsls2forge
dependencies:
  - python=3.7
  - bokeh=1.4.0
  - dask=2.9.1
  - dask-image=0.2.0
  - dask-ml=1.2.0
  # TODO: Bump dask-labextension to >=2 once extensions have been made compatibility updates
  - dask-labextension=1.1.0
  # TODO: Bump jupyterlab to 2.x once extensions have been made compatibility updates
  - ipympl
  - jupyterlab=1.*
  - nodejs
  - notebook<5.7.5
  - tornado=5
  - numba
  - numpy=1.17
  - pandas=0.25.3
  - pyarrow==0.15.1
  - python-graphviz
  - seaborn
  - scikit-learn=0.22
  - matplotlib
  - nbgitpuller
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - bottleneck
  - requests
  - py-xgboost
  - dask-xgboost
  - area-detector-handlers
  - databroker
  - amostra
  - chxtools
 # - py4xs
 # - modestimage
 # - pystackreg
 # - eiger-io
 # - sixtools>=0.0.2
 # - csxtools>=0.1.14
 # - xraylarch>=0.9.45
 # - hxntools
 # - scikit-learn
 # - pyxrf>=0.0.9
 # - mendeleev
 # - netcdf4
 # - numexpr
 # - periodictable
 # - boto3
 # - graphviz
 # - line_profiler
 # - memory_profiler
 # - papermill
 # - pyfai
 # - sasview
 # - fabio
 # - lmfit>=0.9.9
 # - pypdf2
 # - reportlab
 # - scikit-learn
 # - tomopy
 # - xpdan
 # - nslsii
  - pip
  - pip:
    - mimesis
#    - edrixs
    - pyzbar
    - https://github.com/NSLS-II/nsls2-catalogs/archive/v0.0.1.tar.gz
