name: Build Container Image (without pushing)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: update jupyter dependencies with repo2docker
      uses: NSLS-II/repo2docker-action@c64bda966539ff36856055311be7d709605a8a97  # adds support for --appendix
      with:
        NO_PUSH: true
        NOTEBOOK_USER: root
        APPENDIX_FILE: "binder/appendix.txt"
