name: Build Container Image (without pushing)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: update jupyter dependencies with repo2docker
      uses: NSLS-II/repo2docker-action@1e644202ebb90ec704543de23909569294ae2061  # adds support for --appendix
      with:
        NO_PUSH: true
        APPENDIX: "binder/appendix.txt"
